os: osx
osx_image: xcode9.3
language: objective-c
before_install: brew update && brew bundle
install: bundle install
script: bundle exec fastlane ci
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  directories:
  - Carthage
