name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Brew
      run: brew bundle
    - name: Bundle
      run: bundle install
    - name: Save GitHub Token for Carthage
      run: |
        echo "\
        protocol=https
        host=github.com
        username=Nef10
        password=${{ secrets.GITHUB_TOKEN }}
        " | git credential-osxkeychain store
    - name: Test GitHub Token for Carthage
      run: |
        echo "\
        protocol=https
        host=github.com
        username=Nef10
        " | git credential fill
    - name: Fastlane
      run: bundle exec fastlane ci
      env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
